project_id = "ovoldtknfdyvyypadnmf"

[functions.church-discovery]
verify_jwt = false

[functions.church-discovery-apify]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.campaign-management]
verify_jwt = true

[functions.analytics]
verify_jwt = true